# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wacp(object):
    def setupUi(self, wacp):
        wacp.setObjectName("wacp")
        wacp.setEnabled(True)
        wacp.resize(939, 567)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(10)
        wacp.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lccc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        wacp.setWindowIcon(icon)
        wacp.setLayoutDirection(QtCore.Qt.LeftToRight)
        wacp.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(wacp)
        self.centralwidget.setObjectName("centralwidget")
        self.sitelist = QtWidgets.QGroupBox(self.centralwidget)
        self.sitelist.setGeometry(QtCore.QRect(10, 110, 911, 430))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.sitelist.setFont(font)
        self.sitelist.setObjectName("sitelist")
        self.sitetable = QtWidgets.QTableWidget(self.sitelist)
        self.sitetable.setGeometry(QtCore.QRect(10, 35, 891, 385))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sitetable.setFont(font)
        self.sitetable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sitetable.setAutoScroll(True)
        self.sitetable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sitetable.setDragEnabled(True)
        self.sitetable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.sitetable.setShowGrid(True)
        self.sitetable.setGridStyle(QtCore.Qt.SolidLine)
        self.sitetable.setWordWrap(True)
        self.sitetable.setCornerButtonEnabled(True)
        self.sitetable.setRowCount(20)
        self.sitetable.setColumnCount(4)
        self.sitetable.setObjectName("sitetable")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sitetable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sitetable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sitetable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sitetable.setHorizontalHeaderItem(3, item)
        self.sitetable.horizontalHeader().setVisible(True)
        self.sitetable.horizontalHeader().setCascadingSectionResizes(False)
        self.sitetable.horizontalHeader().setDefaultSectionSize(100)
        self.sitetable.horizontalHeader().setStretchLastSection(True)
        self.sitetable.verticalHeader().setCascadingSectionResizes(False)
        self.home_info = QtWidgets.QGroupBox(self.centralwidget)
        self.home_info.setEnabled(True)
        self.home_info.setGeometry(QtCore.QRect(10, 10, 731, 90))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.home_info.setFont(font)
        self.home_info.setObjectName("home_info")
        self.home_name = QtWidgets.QLineEdit(self.home_info)
        self.home_name.setGeometry(QtCore.QRect(10, 55, 141, 25))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.home_name.setFont(font)
        self.home_name.setObjectName("home_name")
        self.home_url = QtWidgets.QLineEdit(self.home_info)
        self.home_url.setGeometry(QtCore.QRect(160, 55, 401, 25))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.home_url.setFont(font)
        self.home_url.setObjectName("home_url")
        self.label_name = QtWidgets.QLabel(self.home_info)
        self.label_name.setGeometry(QtCore.QRect(15, 32, 58, 16))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.label_url = QtWidgets.QLabel(self.home_info)
        self.label_url.setGeometry(QtCore.QRect(165, 32, 58, 16))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_url.setFont(font)
        self.label_url.setObjectName("label_url")
        self.home_apply = QtWidgets.QPushButton(self.home_info)
        self.home_apply.setGeometry(QtCore.QRect(570, 55, 70, 25))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.home_apply.setFont(font)
        self.home_apply.setObjectName("home_apply")
        self.home_delete = QtWidgets.QPushButton(self.home_info)
        self.home_delete.setGeometry(QtCore.QRect(650, 55, 70, 25))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.home_delete.setFont(font)
        self.home_delete.setObjectName("home_delete")
        self.check_af = QtWidgets.QCheckBox(self.home_info)
        self.check_af.setGeometry(QtCore.QRect(572, 25, 101, 30))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check_af.setFont(font)
        self.check_af.setObjectName("check_af")
        self.check_config = QtWidgets.QGroupBox(self.centralwidget)
        self.check_config.setGeometry(QtCore.QRect(750, 10, 170, 91))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.check_config.setFont(font)
        self.check_config.setObjectName("check_config")
        self.spin_cycle = QtWidgets.QSpinBox(self.check_config)
        self.spin_cycle.setGeometry(QtCore.QRect(90, 25, 50, 20))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spin_cycle.setFont(font)
        self.spin_cycle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spin_cycle.setMinimum(1)
        self.spin_cycle.setMaximum(10)
        self.spin_cycle.setSingleStep(1)
        self.spin_cycle.setObjectName("spin_cycle")
        self.label_cycle = QtWidgets.QLabel(self.check_config)
        self.label_cycle.setGeometry(QtCore.QRect(10, 25, 71, 20))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_cycle.setFont(font)
        self.label_cycle.setObjectName("label_cycle")
        self.label_min = QtWidgets.QLabel(self.check_config)
        self.label_min.setGeometry(QtCore.QRect(143, 25, 21, 20))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_min.setFont(font)
        self.label_min.setObjectName("label_min")
        self.start = QtWidgets.QPushButton(self.check_config)
        self.start.setGeometry(QtCore.QRect(10, 55, 70, 25))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.check_config)
        self.stop.setGeometry(QtCore.QRect(90, 55, 70, 25))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stop.setFont(font)
        self.stop.setObjectName("stop")
        wacp.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(wacp)
        self.statusBar.setObjectName("statusBar")
        wacp.setStatusBar(self.statusBar)

        self.retranslateUi(wacp)
        QtCore.QMetaObject.connectSlotsByName(wacp)

    def retranslateUi(self, wacp):
        _translate = QtCore.QCoreApplication.translate
        wacp.setWindowTitle(_translate("wacp", "WACP by Lee"))
        self.sitelist.setTitle(_translate("wacp", "홈페이지 목록"))
        self.sitetable.setSortingEnabled(False)
        item = self.sitetable.horizontalHeaderItem(0)
        item.setText(_translate("wacp", "이름"))
        item = self.sitetable.horizontalHeaderItem(1)
        item.setText(_translate("wacp", "URL"))
        item = self.sitetable.horizontalHeaderItem(2)
        item.setText(_translate("wacp", "최근 점검"))
        item = self.sitetable.horizontalHeaderItem(3)
        item.setText(_translate("wacp", "점검결과"))
        self.home_info.setTitle(_translate("wacp", "홈페이지 정보"))
        self.label_name.setText(_translate("wacp", "이름"))
        self.label_url.setText(_translate("wacp", "URL"))
        self.home_apply.setText(_translate("wacp", "적용"))
        self.home_delete.setText(_translate("wacp", "삭제"))
        self.check_af.setText(_translate("wacp", "군내 사이트"))
        self.check_config.setTitle(_translate("wacp", "점검 설정"))
        self.label_cycle.setText(_translate("wacp", "점검 주기"))
        self.label_min.setText(_translate("wacp", "분"))
        self.start.setText(_translate("wacp", "점검"))
        self.stop.setText(_translate("wacp", "중지"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wacp = QtWidgets.QMainWindow()
    ui = Ui_wacp()
    ui.setupUi(wacp)
    wacp.show()
    sys.exit(app.exec_())

